language: objective-c
osx_image: xcode9
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6 (9.3" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
script:
  - cd Conversation-Samples
  - cd ConversationDemo
  - pod update --repo-update
  - xcodebuild -scheme ConversationDemo -workspace  ConversationDemo.xcworkspace
notifications:
  email:
    recipients:
      - eliza.koren@logmein.com
      - Nissim.Pardo@logmein.com
      - Tony.Shlifstein@logmein.com
      - Oz.BenOved@logmein.com
    on_success: change
    on_failure: always
