language: objective-c
osx_image: xcode9
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
script:
  - cd Conversation-Samples
  - cd HistorySample
  - pod update --repo-update
  - xcodebuild -allowProvisioningUpdates -scheme HistorySample -workspace HistorySample.xcworkspace
notifications:
  email:
    recipients:
      - eliza.koren@logmein.com
      - Nissim.Pardo@logmein.com
      - Tony.Shlifstein@logmein.com
      - Oz.BenOved@logmein.com
    on_success: change
    on_failure: change
